import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '../../context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className=" w-[100%] min-h-[100vh] m-auto  pl-24 pr-24  flex flex-col justify-between">
              <Navbar />
              {children}
              <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
